# Generated by Django 2.0.2 on 2018-02-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('label', models.CharField(max_length=50)),
                ('liquidation_email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
