stages:
- test
- smoke
- deploy

.tox: &tox
  stage: test
  image: jpic/tox
  before_script:
  - tar -xzf .gitlab-cache.tar.gz -C / || true
  after_script:
  - tar -czf .gitlab-cache.tar.gz /root/.cache/pip /root/.local || true
#
# py-qa:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-qa
#   script: tox -e qa
#
# py-test:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-django
#   services:
#   - postgres:10
#   script:
#   - DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR
#     DB_USER=postgres
#     tox --sitepackages -e py36-dj21 -- -x
#
# docs-qa:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-docs
#   script: tox -e docs
#
# js-qa:
#   stage: test
#   image: node:10
#   script:
#   - yarn install
#   - yarn run lint
#
# js-test:
#   stage: test
#   image: node:10
#   script:
#   - yarn install
#   - yarn run test

docker-build:
  stage: test
  image: docker:dind
  before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
  - docker build -t betagouv/mrs:$CI_COMMIT_SHA .
  - docker push betagouv/mrs:$CI_COMMIT_SHA
  - docker tag betagouv/mrs:$CI_COMMIT_SHA betagouv/mrs:$CI_COMMIT_REF_NAME
  - docker push betagouv/mrs:$CI_COMMIT_REF_NAME

smoke:
  stage: smoke
  image: betagouv/mrs:$CI_COMMIT_SHA
  script:
  - export HOST=localhost:8000
  - DEBUG=1 mrs migrate
  - echo 'from institution.models import Institution; Institution.objects.create(finess=310000000, origin="http://$HOST")' | DEBUG=1 mrs shell
  - DEBUG=1 mrs runserver $HOST &
  - until curl $HOST; do sleep 1; done
  - cd /code && node_modules/.bin/jest src/mrs/static/js/smoke.test.js

deploy_staging:
  stage: deploy
  script:
  - echo $SSH_PRIVKEY > ~/.ssh/id_rsa
  - ./.circleci/deploy.sh
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master
