stages:
- test
- smoke
- deploy

.tox: &tox
  stage: test
  image: jpic/tox
  before_script:
  - tar -xzf .gitlab-cache.tar.gz -C / || true
  after_script:
  - tar -czf .gitlab-cache.tar.gz /root/.cache/pip /root/.local || true
#
# py-qa:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-qa
#   script: tox -e qa
#
# py-test:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-django
#   services:
#   - postgres:10
#   script:
#   - DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR
#     DB_USER=postgres
#     tox --sitepackages -e py36-dj21 -- -x
#
# docs-qa:
#   <<: *tox
#   cache:
#     paths: [.gitlab-cache.tar.gz]
#     key: ${CI_COMMIT_REF_SLUG}-docs
#   script: tox -e docs
#
# js-qa:
#   stage: test
#   image: node:10
#   script:
#   - yarn install
#   - yarn run lint
#
# js-test:
#   stage: test
#   image: node:10
#   script:
#   - yarn install
#   - yarn run test

docker-build:
  stage: test
  image: docker:dind
  before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
  - docker build -t betagouv/mrs:$CI_COMMIT_SHA .
  - docker push betagouv/mrs:$CI_COMMIT_SHA
  - docker tag betagouv/mrs:$CI_COMMIT_SHA betagouv/mrs:$CI_COMMIT_REF_NAME
  - docker push betagouv/mrs:$CI_COMMIT_REF_NAME

smoke:
  stage: smoke
  image: betagouv/mrs:$CI_COMMIT_SHA
  services:
  - postgres:10
  - name: betagouv/mrs:$CI_COMMIT_SHA
    alias: mrs
#    entrypoint: [sh]
#    command:
#    - "-c"
#    - "ALLOWED_HOSTS='*' SECRET_KEY=itsnotsecret mrs runserver 0:6789"
    entrypoint: [uwsgi]
# if using uwsgi:
    command:
    - --env=DJANGO_SETTINGS_MODULE=mrs.settings
    - --env=ALLOWED_HOSTS=localhost
    - --env=SECRET_KEY=itsnotsecret
    - --env=LOG=log
    - --env=DB_HOST=postgres
    - --env=DB_NAME=postgres
    - --env=DB_USER=postgres
    - --env=DB_ENGINE=django.db.backends.postgresql
    - --env=DEBUG=1
    - --spooler=/spooler/stat
    - --spooler=/spooler/mail
    - --spooler-processes=1
    - --http-socket=:6789
    - --plugin=python3
    - --module=mrs.wsgi:application
  script:
  - export HOST=http://$BETAGOUV_MRS_PORT_6789_TCP_ADDR:6789
  - export DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR
  - export DB_USER=postgres
  - export DB_NAME=postgres
  - export DB_ENGINE=django.db.backends.postgresql
  - DEBUG=1 mrs migrate
  - echo 'from institution.models import Institution; Institution.objects.create(finess=310000000, origin="$HOST")' | DEBUG=1 mrs shell
  - until curl $HOST; do sleep 1; done
  - cd /code && node_modules/.bin/jest src/mrs/static/js/smoke.test.js

deploy_staging:
  stage: deploy
  script:
  - echo $SSH_PRIVKEY > ~/.ssh/id_rsa
  - ./.circleci/deploy.sh
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - master
