stages:
- test
- build
- smoke
- deploy

py-qa:
  stage: test
  image: python:3.7
  cache:
    key: ${CI_COMMIT_REF_SLUG}-qa
    paths: [.tox]
  script:
  - pip install tox
  - tox -e qa

py-test:
  stage: test
  image: python:3.7
  cache:
    key: ${CI_COMMIT_REF_SLUG}-django
    paths: [.tox]
  script:
  - pip install tox
  - tox -e py37-dj21

docs-qa:
  stage: test
  image: python:3.7
  cache:
    key: ${CI_COMMIT_REF_SLUG}-docs
    paths: [.tox]
  script:
  - pip install tox
  - tox -e docs

js-qa:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run lint

js-test:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run test

docker-build:
  stage: build
  image: docker:dind
  script:
  - docker build -t mrs-test .
