stages:
- build
- test
- release
- staging
- ecole
- production

variables:
  ANSIBLE_FORCE_COLOR: "1"

.deploy: &deploy
  stage: staging
  variables:
    TIMEOUT: 1200
  image: yourlabs/playlabs:master
  script:
  - playlabs git clone $INVENTORY_REPOSITORY
  - playlabs deploy prefix=mrs instance=$CI_ENVIRONMENT_SLUG image=betagouv/mrs:$CI_COMMIT_SHA deploy@ --tags=update

docker:
  stage: build
  image: docker:dind
  before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
  - docker build
        --shm-size 512M
        -t betagouv/mrs:$CI_COMMIT_SHA
        --build-arg GIT_COMMIT=$CI_COMMIT_SHA
        .
  - docker push
        betagouv/mrs:$CI_COMMIT_SHA
  - docker tag
        betagouv/mrs:$CI_COMMIT_SHA
        betagouv/mrs:$CI_COMMIT_REF_NAME
  - docker push
        betagouv/mrs:$CI_COMMIT_REF_NAME

py-sec-bandit:
  stage: build
  image: yourlabs/python
  script: bandit -v -x commands,tests {posargs:-r src}

py-sec-safety:
  stage: build
  image: yourlabs/python
  script: safety check

py-qa:
  stage: build
  image: yourlabs/python
  script: ./sh.yml py.qa

py-test:
  stage: test
  image: betagouv/mrs:$CI_COMMIT_SHA
  services:
  - postgres:10
  script:
  - DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR
    DB_USER=postgres
    venv=none cov=src ./sh.yml py.test

js-qa:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run lint

js-test:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run test
  - npm install -g codecov
  - codecov
    --token $CODECOV_TOKEN
    -e $TOXENV

docs-qa:
  image: yourlabs/python
  script: mkdir -p docs/_static && sphinx-build -n -W docs/ docs/_build/

js-acceptance:
  stage: release
  image: betagouv/mrs:$CI_COMMIT_SHA
  script:
  - export HOST=localhost:8000
  - DEBUG=1 mrs migrate
  - echo 'from institution.models import Institution; Institution.objects.create(finess=310000000, origin="http://$HOST")' | DEBUG=1 mrs shell
  - cd /app && DEBUG=1 mrs runserver $HOST &
  - until curl $HOST; do sleep 1; done
  - cd /app && node_modules/.bin/jest src/mrs/static/js/smoke.test.js

deploy-jpic:
  <<: *deploy
  only:
    refs: [jpic]
  environment:
    name: jpic
    url: https://jpic.mrs.yourlabs.org

deploy-tbinetruy:
  <<: *deploy
  only:
    refs: [tbinetruy]
  environment:
    name: tbinetruy
    url: https://tbinetruy.mrs.yourlabs.org

deploy-vince:
  <<: *deploy
  only:
    refs: [vindarel]
  environment:
    name: vince
    url: https://vince.mrs.yourlabs.org

deploy-staging:
  <<: *deploy
  only:
    refs: [master]
  environment:
    name: staging
    url: https://staging.mrs.beta.gouv.fr

deploy-ecole:
  <<: *deploy
  stage: ecole
  only:
    refs: [master]
  environment:
    name: ecole
    url: https://ecole.mrs.beta.gouv.fr

deploy-production:
  <<: *deploy
  stage: production
  when: manual
  only:
    refs: [master]
  environment:
    name: production
    url: https://mrs.beta.gouv.fr
