stages:
- test
- release
- staging
- ecole
- production

variables:
  ANSIBLE_FORCE_COLOR: 1

.deploy: &deploy
  stage: staging
  image: yourlabs/playlabs:master
  script:
  - playlabs git clone $INVENTORY_REPOSITORY
  - playlabs deploy prefix=mrs instance=$CI_ENVIRONMENT_SLUG image=betagouv/mrs:$CI_COMMIT_SHA --user=deploy --nosudo --tags=update

.tox: &tox
  stage: test
  image: jpic/tox

.sentry: &sentry
  stage: release
  image: betagouv/mrs:$CI_COMMIT_SHA
  script:
  - /app/node_modules/.bin/sentry-cli releases new $CI_COMMIT_SHA
  - /app/node_modules/.bin/sentry-cli releases set-commits $CI_COMMIT_SHA --commit "betagouv/mrs@$CI_COMMIT_SHA"
  - cd /app && yarn prepare

docker:
  stage: test
  image: docker:dind
  before_script:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  script:
  - docker build --shm-size 256M -t betagouv/mrs:$CI_COMMIT_SHA --build-arg GIT_COMMIT=$CI_COMMIT_SHA .
  - docker push betagouv/mrs:$CI_COMMIT_SHA
  - docker tag betagouv/mrs:$CI_COMMIT_SHA betagouv/mrs:$CI_COMMIT_REF_NAME
  - docker push betagouv/mrs:$CI_COMMIT_REF_NAME

py-qa:
  <<: *tox
  script: tox -e qa

py-test:
  <<: *tox
  services:
  - postgres:10
  script:
  - DB_HOST=$POSTGRES_PORT_5432_TCP_ADDR
    DB_USER=postgres
    tox --sitepackages -e py36-dj21 -- -x
  - PATH=.tox/py36-dj21/bin:$PATH
    codecov --token $CODECOV_TOKEN
    -e $TOXENV

js-qa:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run lint

js-test:
  stage: test
  image: node:10
  script:
  - yarn install
  - yarn run test
  - npm install -g codecov
  - codecov
    --token $CODECOV_TOKEN
    -e $TOXENV

docs-qa:
  <<: *tox
  script: tox -e docs

smoke:
  stage: release
  image: betagouv/mrs:$CI_COMMIT_SHA
  script:
  - export HOST=localhost:8000
  - DEBUG=1 mrs migrate
  - echo 'from institution.models import Institution; Institution.objects.create(finess=310000000, origin="http://$HOST")' | DEBUG=1 mrs shell
  - cd /app && DEBUG=1 mrs runserver $HOST &
  - until curl $HOST; do sleep 1; done
  - cd /app && node_modules/.bin/jest src/mrs/static/js/smoke.test.js

sentry-dev:
  <<: *sentry
  variables:
    SENTRY_PROJECT: mrs-dev
  except:
    refs: [master]

sentry-production:
  <<: *sentry
  variables:
    SENTRY_PROJECT: mrs-production
  only:
    refs: [master]

jpic:
  <<: *deploy
  only:
    refs: [jpic]
  environment:
    name: jpic
    url: https://jpic.mrs.yourlabs.org

tbinetruy:
  <<: *deploy
  only:
    refs: [tbinetruy]
  environment:
    name: tbinetruy
    url: https://tbinetruy.mrs.yourlabs.org

vince:
  <<: *deploy
  only:
    refs: [vindarel]
  environment:
    name: vince
    url: https://vince.mrs.yourlabs.org

staging:
  <<: *deploy
  only:
    refs: [master]
  environment:
    name: staging
    url: https://staging.mrs.beta.gouv.fr

ecole:
  <<: *deploy
  stage: ecole
  only:
    refs: [master]
  environment:
    name: ecole
    url: https://ecole.mrs.beta.gouv.fr

production:
  <<: *deploy
  stage: production
  when: manual
  only:
    refs: [master]
  environment:
    name: production
    url: https://mrs.beta.gouv.fr
