version: '3.7'
services:
  django:
    environment:
    - HOST
    - ALLOWED_HOSTS=${HOST}
    - SENTRY_AUTH_TOKEN
    - SENTRY_DSN
    - SENTRY_ORG=sentry
    - SENTRY_PROJECT
    - SENTRY_URL
    - TEAM_EMAIL
    - BASICAUTH_ENABLE
    labels:
    - "traefik.enable=true"
    - "traefik.frontend.rule=Host: ${HOST}"
    - "traefik.port=8000"
    - "io.yourlabs.compose.mkdir=./log:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler/mail:1000:1000:0750"
    - "io.yourlabs.compose.mkdir=./spooler/stat:1000:1000:0750"
    networks:
    - default
    - web

  postgres:
    networks:
    - default

networks:
  web:
    external: true
