version: '3.7'
services:
  django:
    environment:
    - HOST
    - ALLOWED_HOSTS=${HOST}
    - SENTRY_AUTH_TOKEN
    - SENTRY_DSN
    - SENTRY_ORG=sentry
    - SENTRY_PROJECT
    - SENTRY_URL
    - TEAM_EMAIL
    - BASICAUTH_DISABLE
    labels:
    - "traefik.enable=true"
    - "traefik.port=8000"
    - "traefik.frontend.rule=Host: ${HOST},www.${HOST}"
    - "traefik.frontend.redirect.regex=^https?://${HOST}/(.*)"
    - "traefik.frontend.redirect.replacement=https://www.${HOST}/$${1}"
    - "traefik.frontend.redirect.permanent=true"
    networks:
    - default
    - web

  postgres:
    networks:
    - default

networks:
  web:
    external: true
