# Generated by Django 2.0.3 on 2018-04-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nom')),
                ('subject', models.CharField(max_length=255, verbose_name='Modèle de sujet')),
                ('body', models.TextField(verbose_name='Modèle de contenu')),
                ('active', models.BooleanField(default=True, verbose_name='Cocher si actif')),
            ],
            options={
                'verbose_name': "Modèle d'email",
                'verbose_name_plural': "Modèles d'emails",
                'ordering': ('name',),
            },
        ),
    ]
