# Generated by Django 2.0.3 on 2018-03-23 15:16

from django.db import migrations


def provision_initial_templates(apps, schema_editor):
    EmailTemplate = apps.get_model('mrsemail', 'EmailTemplate')
    EmailTemplate.objects.update_or_create(
        name='PMT: Trajet limité à 1 A/R',
        defaults=dict(
            subject='Demande {{ display_id }} invalidée pour prescription médicale limitée à un trajet Aller-Retour',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter en l'état. Vous avez sollicité une prise en charge pour plusieurs trajets alors que votre prescription médicale a été établie pour un trajet unique.

Nous vous invitons à renouveler votre demande sur notre site en ajustant votre déclaration.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )
    EmailTemplate.objects.update_or_create(
        name='PMT: Date postérieure au transport',
        defaults=dict(
            subject='Demande {{ display_id }} invalidée pour date de prescription postérieure au transport',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter. La prescription médicale de transport doit être réalisée avant le trajet.

Dans votre déclaration, la date du transport est antérieure à la date de prescription de votre transport par votre médecin.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )
    EmailTemplate.objects.update_or_create(
            name='Frais: Montant PJ et dépense incohérentes',
        defaults=dict(
            subject='Demande {{ display_id }} invalidée pour pièces justificatives non conformes aux frais déclarés',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter car les pièces justificatives transmises pour la prise en charge de vos frais de péage et/ou de stationnement ne correspondent pas au montant déclaré.

Pour rappel, nous calculons automatiquement les frais kilométriques à partir du nombre de kilomètres déclarés. Il convient d'indiquer dans les frais uniquement les frais de stationnement ou de péage.

Nous vous invitons à renouveler votre demande sur notre site en joignant le document manquant ou en corrigeant votre saisie.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )

    EmailTemplate.objects.update_or_create(
        name='PMT: Incomplète',
        defaults=dict(
            subject='Demande {{ display_id }} invalidée pour prescription médicale de transports incomplète',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter en l'état. Votre médecin n’a pas indiqué, dans la prescription médicale de transport, la situation vous ouvrant droit à la prise en charge de votre transport.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )

    EmailTemplate.objects.update_or_create(
        name='PMT: absente',
        defaults=dict(
            subject='Demande {{ display_id }} invalidée pour absence de prescription médicale de transports',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas la traiter car vous n'avez pas transmis votre prescription médicale de transport. La prise en charge des transports est soumise à prescription médicale.

Nous vous invitons à renouveler votre demande en joignant ce document.

Pour en savoir plus, consultez la rubrique : https://www.mrs.beta.gouv.fr/faq

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )

    EmailTemplate.objects.update_or_create(
        name='Document illisible',
        defaults=dict(
            subject='Problème avec votre demande de remboursement MRS n°{{ display_id }}',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.

Nous ne pouvons toutefois pas y donner suite pour le motif suivant :

<*********** A MODIFIER **********>
Indiquer la nature du document illisible ou erroné (pièces en rouge)>
<*********************************>

Nous vous invitons à renouveler votre demande en y joignant les documents plus lisibles.

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )

    EmailTemplate.objects.update_or_create(
        name='Justificatif: Manquant',
        defaults=dict(
            subject='Problème avec votre demande de remboursement MRS n°{{ display_id }}',
            body='''
Bonjour,

Nous avons bien reçu votre demande de remboursement de vos frais de transport.
Nous ne pouvons la traiter en l'état .

Vous ne nous avez pas transmis le justificatif de paiement de :
<*********** A MODIFIER **********>
-	Vos frais de stationnement ou de péage (au choix selon la situation)
<*********************************>

Nous vous invitons à renouveler votre demande directement en ligne en joignant les documents manquants.

Bien cordialement,
L'équipe MRS
'''.strip()
        )
    )



class Migration(migrations.Migration):

    dependencies = [
        ('mrsemail', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(provision_initial_templates),
    ]
