# Generated by Django 2.1 on 2018-10-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsemail', '0002_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='menu',
            field=models.CharField(choices=[('reject', 'Rejet'), ('contact', 'Contact')], db_index=True, default='reject', max_length=10),
        ),
    ]
