# Generated by Django 2.1.8 on 2019-04-24 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsemail', '0005_counter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplate',
            options={'ordering': ('name',), 'verbose_name': 'Gabarit'},
        ),
    ]
