# Generated by Django 2.0.3 on 2018-04-13 22:08

from django.db import migrations, models
import institution.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finess', models.IntegerField(validators=[institution.models.institution_finess])),
                ('origin', models.CharField(help_text='URI du site patients', max_length=255)),
                ('dynamic_allow', models.BooleanField(default=False, help_text="Cocher pour les hebergeurs non-HDS qui ne veulent pas de controle d'origine", verbose_name='Autorisation CORS dynamique')),
            ],
            options={
                'verbose_name': 'Établissement',
                'ordering': ['finess'],
            },
        ),
    ]
