# Generated by Django 2.0.5 on 2018-06-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='finess',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='origin',
            field=models.CharField(default='', help_text='URI du site patients', max_length=255),
        ),
    ]
