# Generated by Django 2.0.2 on 2018-02-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='origin',
            field=models.CharField(default='', help_text='URI du site patients', max_length=255),
            preserve_default=False,
        ),
    ]
