# Generated by Django 2.0.2 on 2018-02-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_institution_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['finess'], 'verbose_name': 'Établissement'},
        ),
        migrations.AddField(
            model_name='institution',
            name='dynamic_allow',
            field=models.BooleanField(default=False, help_text='Cocher pour les hebergeurs non-HDS qui veulent leur iframe en mode passoire', verbose_name='Autorisation CORS dynamique'),
        ),
    ]
