# Generated by Django 2.0 on 2017-12-06 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.FileField(upload_to='', verbose_name='Prescription Médicale de Transport')),
                ('aller_date', models.DateField(verbose_name="Date d'aller")),
                ('retour_date', models.DateField(verbose_name='Date de retour')),
                ('distance', models.IntegerField(verbose_name='Kilométrage total parcouru')),
                ('frais', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Montant total des frais (parking et/ ou péage)')),
                ('insured', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insured_transport_set', to='person.Person')),
                ('transported', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transported_transport_set', to='person.Person')),
            ],
        ),
    ]
