# Generated by Django 2.0 on 2017-12-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrsrequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('document', models.BinaryField(verbose_name='Prescription Médicale de Transport')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'ordering': ['transport', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(verbose_name="Date d'aller")),
                ('date_return', models.DateField(verbose_name='Date de retour')),
                ('distance', models.IntegerField(verbose_name='Kilométrage total parcouru')),
                ('expense', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Montant total des frais (parking et/ ou péage)')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest')),
            ],
            options={
                'ordering': ['request'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.Transport'),
        ),
    ]
