# Generated by Django 2.0 on 2017-12-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='distance',
            field=models.PositiveIntegerField(help_text='Kilométrage total parcouru', null=True, verbose_name='Distance (km)'),
        ),
    ]
