# Generated by Django 2.0 on 2017-12-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='date_depart',
            field=models.DateField(help_text='Date du trajet aller', null=True, verbose_name='Aller'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_return',
            field=models.DateField(help_text='Date du trajet retour', null=True, verbose_name='Retour'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='distance',
            field=models.IntegerField(help_text='Kilométrage total parcouru', null=True, verbose_name='Distance (km)'),
        ),
    ]
