# Generated by Django 2.2.3 on 2019-10-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsattachment', '0002_add_attachment_file_null_binary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrsattachment',
            name='binary',
        ),
    ]
