# Generated by Django 2.0.2 on 2018-02-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsattachment', '0002_mrsattachment_mimetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrsattachment',
            name='mimetype',
        ),
    ]
