# Generated by Django 2.0.3 on 2018-04-13 22:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mrsrequest.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrsattachment', '0001_initial'),
        ('institution', '0001_initial'),
        ('person', '0001_initial'),
        ('mrsemail', '0001_initial'),
        ('caisse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('mrsattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrsattachment.MRSAttachment')),
            ],
            options={
                'verbose_name': 'Justificatif',
                'ordering': ['mrsrequest', 'id'],
            },
            bases=('mrsattachment.mrsattachment',),
        ),
        migrations.CreateModel(
            name='MRSRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_datetime', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure de la demande')),
                ('creation_ip', models.GenericIPAddressField(null=True)),
                ('display_id', models.IntegerField(unique=True, verbose_name='Numéro de demande')),
                ('status_datetime', models.DateTimeField(db_index=True, null=True, verbose_name='Date et heure de changement de statut')),
                ('distance', models.PositiveIntegerField(help_text='Total des kilomètres parcourus', null=True, verbose_name='Distance (km)')),
                ('expense', models.DecimalField(decimal_places=2, default=0, help_text='Somme totale des frais de stationnement et/ou péage et/ou de transport en commun', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total des frais (en € TTC)')),
                ('status', models.IntegerField(choices=[(0, 'Soumise'), (1, 'Validée'), (2, 'Rejetée')], default=0, verbose_name='Statut')),
                ('caisse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.Caisse')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.Institution')),
                ('insured', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.Person')),
                ('reject_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrsemail.EmailTemplate')),
                ('status_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du changement de statut')),
            ],
            options={
                'verbose_name': 'Demande',
                'ordering': ['-creation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='PMT',
            fields=[
                ('mrsattachment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mrsattachment.MRSAttachment')),
                ('mrsrequest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest')),
            ],
            options={
                'ordering': ['mrsrequest', 'id'],
            },
            bases=('mrsattachment.mrsattachment',),
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depart', models.DateField(help_text='Date du trajet aller', null=True, validators=[mrsrequest.models.transport_date_validate], verbose_name='Aller')),
                ('date_return', models.DateField(help_text='Date du trajet retour', null=True, validators=[mrsrequest.models.transport_date_validate], verbose_name='Retour')),
                ('mrsrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest')),
            ],
            options={
                'ordering': ['mrsrequest', 'date_depart'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='mrsrequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest'),
        ),
    ]
