# Generated by Django 2.0.4 on 2018-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('update mrsrequest_mrsrequest set status=9 where status=1'),
        migrations.RunSQL('update mrsrequest_mrsrequest set status=1 where status=2'),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Soumise'), (1, 'Rejetée'), (9, 'Validée')], default=0, verbose_name='Statut'),
        ),
    ]
