# Generated by Django 2.0.4 on 2018-04-26 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0002_status_inprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='reject_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrsemail.EmailTemplate'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Soumise'), (1, 'Rejetée'), (2, 'En cours'), (9, 'Validée')], default=0, verbose_name='Statut'),
        ),
    ]
