# Generated by Django 2.0.1 on 2018-02-05 16:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mrsrequest.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrsrequest', '0002_mrsrequest_form_id_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='status_datetime',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Date et heure de changement de statut'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='status_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du changement de statut'),
        ),
    ]
