# Generated by Django 2.2.3 on 2019-12-10 10:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0002_squashed_migrations_step2'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='convocation',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Date de convocation médicale'),
        ),
    ]
