# Generated by Django 2.0.1 on 2018-02-05 16:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import mrsrequest.models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0003_log_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrsrequest',
            options={'ordering': ['-creation_datetime'], 'verbose_name': 'Demande'},
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='creation_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure de la demande'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Parking et/ou péage ou justificatif(s) de transport en commun', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total des frais (en € TTC)'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(0, 'Soumise'), (1, 'Validée'), (2, 'Rejetée')], default=0, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_depart',
            field=models.DateField(help_text='Date du trajet aller', null=True, validators=[mrsrequest.models.transport_date_validate], verbose_name='Aller'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_return',
            field=models.DateField(help_text='Date du trajet retour', null=True, validators=[mrsrequest.models.transport_date_validate], verbose_name='Retour'),
        ),
    ]
