# Generated by Django 2.0.5 on 2018-06-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0004_mrsrequest_logentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='insured_shift',
            field=models.NullBooleanField(default=None, verbose_name='Assuré qui bascule'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='mandate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de mandatement'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Montant remboursé'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='payment_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Base de remboursement'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Soumise'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée')], default=1, verbose_name='Statut'),
        ),
    ]
