# Generated by Django 2.0.5 on 2018-06-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0005_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='display_id',
            field=models.BigIntegerField(unique=True, verbose_name='Numéro de demande'),
        ),
    ]
