# Generated by Django 2.0.5 on 2018-06-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0006_display_id_bigint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='status_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Date et heure de changement de statut'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur du changement de statut'),
        ),
    ]
