# Generated by Django 2.0.2 on 2018-02-26 08:38

import os
from django.db import migrations, models
import django.db.models.deletion


def set_initial_cpam(apps, schema_editor):
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    CPAM = apps.get_model('cpam', 'CPAM')
    initial, created = CPAM.objects.update_or_create(
        code='123123123',
        defaults=dict(
            label='CPAM Haute Garonne',
            liquidation_email=os.getenv('LIQUIDATION_EMAIL', 'liquidation@example.com')
        )
    )
    MRSRequest.objects.filter(cpam=None).update(cpam=initial)


class Migration(migrations.Migration):

    dependencies = [
        ('cpam', '0001_initial'),
        ('mrsrequest', '0007_add_institution_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='cpam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpam.CPAM'),
        ),
        migrations.RunPython(set_initial_cpam),
        migrations.AlterField(
            model_name='mrsrequest',
            name='cpam',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='cpam.CPAM'),
        ),
        # Some backlog
        migrations.AlterField(
            model_name='mrsrequest',
            name='display_id',
            field=models.IntegerField(unique=True, verbose_name='Numéro de demande'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='distance',
            field=models.PositiveIntegerField(help_text='Total des kilomètres parcourus', null=True, verbose_name='Distance (km)'),
        ),
    ]
