# Generated by Django 2.0.5 on 2018-06-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0007_status_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='adeli',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
