# Generated by Django 2.0.2 on 2018-02-26 08:38

import os
from django.db import migrations, models
import django.db.models.deletion


def set_initial_caisse(apps, schema_editor):
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    Caisse = apps.get_model('caisse', 'Caisse')
    initial = Caisse.objects.get(number=311)
    MRSRequest.objects.filter(caisse=None).update(caisse=initial)


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0002_initial_data'),
        ('mrsrequest', '0007_add_institution_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='caisse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.Caisse'),
        ),
        migrations.RunPython(set_initial_caisse, reverse_code=migrations.RunPython.noop),
    ]
