# Generated by Django 2.0.3 on 2018-04-05 12:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsemail', '0003_bichonage_verbose_names'),
        ('mrsrequest', '0008_add_caisse_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='reject_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrsemail.EmailTemplate'),
        ),
    ]
