# Generated by Django 2.0.5 on 2018-06-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0008_mrsrequest_adeli'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='delay',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='saving',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='taxi_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True),
        ),
    ]
