# Generated by Django 2.0.3 on 2018-04-05 12:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0009_mrsrequest_reject_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['mrsrequest', 'date_depart']},
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='display_id',
            field=models.IntegerField(unique=True, verbose_name='Numéro de demande'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='distance',
            field=models.PositiveIntegerField(help_text='Total des kilomètres parcourus', null=True, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme totale des frais de stationnement et/ou péage et/ou de transport en commun', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant total des frais (en € TTC)'),
        ),
    ]
