# Generated by Django 2.0.5 on 2018-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0009_delay_saving_taxi_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='saving',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='taxi_cost',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
