# Generated by Django 2.0.5 on 2018-06-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0011_insured_shift_move_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='insured_shift',
            field=models.NullBooleanField(default=None, verbose_name='Assuré a basculé sur cette demande'),
        ),
    ]
