# Generated by Django 2.0.5 on 2018-07-03 10:44

import datetime
import django.core.validators
from django.db import migrations, models
import mrsrequest.models


def fix_y2k(apps, schema_editor):
    Transport = apps.get_model('mrsrequest', 'Transport')
    transports = Transport.objects.filter(
        models.Q(date_depart__year__lt=100) | models.Q(date_return__year__lt=100),
        mrsrequest__status__gte=1000,
    ).select_related('mrsrequest')

    for t in transports:
        if t.date_depart.year < 100:
            print(t.mrsrequest.display_id, 'old date depart', t.date_depart)
            t.date_depart = datetime.date(
                year=t.date_depart.year + 2000,
                month=t.date_depart.month,
                day=t.date_depart.day,
            )
            print(t.mrsrequest.display_id, 'new date depart', t.date_depart)

        if t.date_return.year < 100:
            print(t.mrsrequest.display_id, 'old date return', t.date_return)
            t.date_return = datetime.date(
                year=t.date_return.year + 2000,
                month=t.date_return.month,
                day=t.date_return.day,
            )
            print(t.mrsrequest.display_id, 'new date return', t.date_return)

        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0012_mrsrequest_insured_shift'),
    ]

    operations = [
        migrations.RunPython(fix_y2k),
        migrations.AlterField(
            model_name='mrsrequest',
            name='mandate_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Date de mandatement'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_depart',
            field=models.DateField(help_text='Date du trajet aller', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), mrsrequest.models.transport_date_validate], verbose_name='Aller'),
        ),
        migrations.AlterField(
            model_name='transport',
            name='date_return',
            field=models.DateField(help_text='Date du trajet retour', null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1)), mrsrequest.models.transport_date_validate], verbose_name='Retour'),
        ),
    ]
