# Generated by Django 2.1 on 2018-09-08 10:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrsrequest', '0013_fix_y2k'),
    ]

    operations = [
        migrations.CreateModel(
            name='MRSRequestLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date et heure')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('action', models.SmallIntegerField(choices=[(1, 'Soumise'), (2, 'Modifiée'), (3, 'Effacée'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée')])),
                ('mrsrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logentries', to='mrsrequest.MRSRequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
