# Generated by Django 2.1 on 2018-09-08 10:42

from django.db import migrations


def admin_to_mrs_logentries(apps, schema_editor):
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    MRSRequestLogEntry = apps.get_model('mrsrequest', 'MRSRequestLogEntry')
    LogEntry = apps.get_model('admin', 'LogEntry')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    c = ContentType.objects.get_for_model(MRSRequest)
    existing = [
        str(i)
        for i in MRSRequest.objects.values_list('pk', flat=True)
    ]

    for l in LogEntry.objects.filter(content_type=c):
        if l.object_id not in existing:
            continue

        MRSRequestLogEntry.objects.create(
            mrsrequest_id=l.object_id,
            user=l.user,
            action=l.action_flag,
            datetime=l.action_time,
            comment=l.change_message,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0014_mrsrequestlogentry'),
    ]

    operations = [
        migrations.RunPython(admin_to_mrs_logentries),
    ]
