# Generated by Django 2.1 on 2018-09-08 10:42

from django.conf import settings
from django.db import migrations
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json


def provision(apps, schema_editor):
    if 'postgres' not in settings.DATABASES['default']['ENGINE']:
        print('Not postgres -> no JSON field')
        return
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    for m in MRSRequest.objects.all():
        if not m.insured:
            continue

        m.data = {
            i: getattr(m.insured, i) for i in (
                'first_name',
                'last_name',
                'nir',
                'email',
                'birth_date',
            )
        }
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0015_migrate_logentries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrsrequestlogentry',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name="Formulaire tel que soumit par l'usager"),
        ),
        migrations.RunPython(provision),
    ]
