# Generated by Django 2.1 on 2018-10-18 18:10

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0016_instance_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrsrequest',
            old_name='expense',
            new_name='expensevp',
        ),
    ]
