# Generated by Django 2.1 on 2018-10-18 18:13

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0017_expense_rename_expensevp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrsrequest',
            old_name='distance',
            new_name='distancevp',
        ),
    ]
