# Generated by Django 2.1 on 2018-10-18 18:36

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0018_distance_rename_distancevp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillVP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mrsrequest.bill',),
        ),
        migrations.AddField(
            model_name='bill',
            name='mode',
            field=models.CharField(choices=[('vp', 'Vehicule Personnel')], db_index=True, default='vp', max_length=3),
        ),
    ]
