# Generated by Django 2.1 on 2018-10-22 16:10

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0019_add_bill_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillATP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('mrsrequest.bill',),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='expenseatp',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Somme totale des frais de transport en commun (en € TTC)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de transports'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='mode',
            field=models.CharField(choices=[('vp', 'Vehicule Personnel'), ('atp', 'Transports en commun')], db_index=True, default='vp', max_length=3),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='distancevp',
            field=models.PositiveIntegerField(help_text='Total des kilomètres parcourus: en cas de transports aller retour, ou de transports itératifs indiquer le nombre total de km parcours. (ex.pour 2 trajets de 40 km, indiquer 80 km)', null=True, verbose_name='Distance (km)'),
        ),
    ]
