# Generated by Django 2.1 on 2018-10-23 09:18

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0020_add_billatp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='modeatp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='modevp',
            field=models.BooleanField(default=True),
        ),
    ]
