# Generated by Django 2.1 on 2018-10-26 11:37

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsemail', '0005_counter'),
        ('mrsrequest', '0021_save_modes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrsrequest',
            name='reject_template',
        ),
    ]
