# Generated by Django 2.1.3 on 2018-11-03 20:47

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0023_mrsrequest_modevp_default_false'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='distancevp',
            field=models.PositiveIntegerField(blank=True, help_text='Total des kilomètres parcourus: en cas de transports aller retour, ou de transports itératifs indiquer le nombre total de km parcours. (ex.pour 2 trajets de 40 km, indiquer 80 km)', null=True, verbose_name='Distance (km)'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expenseatp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Somme totale des frais de transport en commun (en € TTC)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de transports'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expensevp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Somme totale des frais de péage et/ou de transport en commun (en € TTC)', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de péage et/ou transports'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='modeatp',
            field=models.BooleanField(blank=True, default=False, help_text='(Avion, bus, métro, train, bateau…)', verbose_name='Avez vous voyagé en transports en commun ?'),
        ),
        migrations.AlterField(
            model_name='mrsrequestlogentry',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Soumise'), (2, 'Modifiée'), (3, 'Effacée'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée'), (800, 'Contacté')]),
        ),
        migrations.AlterField(
            model_name='mrsrequestlogentry',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
