# Generated by Django 2.1 on 2018-11-30 13:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0026_rename_mandate_date_mandate_datevp'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='mandate_dateatp',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Date de mandatement ATP'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='mandate_datevp',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(datetime.date(2000, 1, 1))], verbose_name='Date de mandatement VP'),
        ),
    ]
