# Generated by Django 2.1 on 2018-11-27 04:14

from django.db import migrations, models


def initial_distancevp(apps, schema_editor):
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    for m in MRSRequest.objects.all():
        m.data['distancevp'] = m.distancevp
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0027_add_mrsrequest_mandate_dateatp'),
    ]

    operations = [
        migrations.RunPython(initial_distancevp),
    ]
