# Generated by Django 2.1 on 2018-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0029_convert_birth_dates_to_fr_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='confirms',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de signalements pour cette demande', verbose_name='Nb. signalements'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='saving',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=8, null=True, verbose_name='économie'),
        ),
    ]
