# Generated by Django 2.1.4 on 2019-01-09 16:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0030_add_mrsrequest_confirms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='expenseatp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Somme totale des frais de transport en commun (en € TTC)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de transports'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expensevp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Somme totale des frais de péage et/ou de transport en commun (en € TTC)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de péage et/ou transports'),
        ),
    ]
