# Generated by Django 2.1.3 on 2019-01-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0031_null_expense_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mrsrequest',
            name='creation_ip',
        ),
    ]
