# Generated by Django 2.1.4 on 2019-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0032_remove_mrsrequest_creation_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrsrequest',
            old_name='confirms',
            new_name='conflicts_accepted',
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='conflicts_accepted',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de signalements acceptés pour cette demande', verbose_name='Nb. signalements acceptés'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='conflicts_resolved',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de signalements résolus avant soumission', verbose_name='Nb. signalements résolus'),
        ),
    ]
