# Generated by Django 2.1.3 on 2019-01-15 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0033_conflicts_counter_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='update_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Link to delete or edit a request'),
        ),
    ]
