# Generated by Django 2.1 on 2019-01-28 18:26

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0033_conflicts_counter_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='update_token',
            field=models.CharField(default=secrets.token_urlsafe, editable=False, max_length=255, verbose_name="Token d'authentification pour modifier la demande"),
        ),
    ]
