# Generated by Django 2.1 on 2019-01-28 18:26

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0033_conflicts_counter_rewrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='token',
            field=models.CharField(null=True, default=None, editable=False, max_length=255, verbose_name="Token d'authentification pour modifier la demande"),
        ),
        # We first called AddField that made null the default for existing
        # requests.
        # Now alter it and make secrets.token_urlsafe the default for new
        # objects from now on.
        migrations.AlterField(
            model_name='mrsrequest',
            name='token',
            field=models.CharField(null=True, default=secrets.token_urlsafe, editable=False, max_length=255, verbose_name="Token d'authentification pour modifier la demande"),
        ),
    ]
