# Generated by Django 2.1.6 on 2019-02-11 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0034_mrsrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Soumise'), (100, 'Annulée'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée')], default=1, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='mrsrequestlogentry',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Soumise'), (2, 'Modifiée'), (3, 'Effacée'), (100, 'Annulée'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée'), (800, 'Contacté')]),
        ),
        migrations.AlterField(
            model_name='mrsrequestlogentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
