# Generated by Django 2.1.6 on 2019-02-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0035_cancel_mrsrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmt',
            name='mrsrequest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest'),
        ),
    ]
