# Generated by Django 2.1.6 on 2019-03-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0036_multiple_pmts'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrsrequest',
            name='suspended',
            field=models.BooleanField(blank=True, db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Soumise'), (100, 'Annulée'), (600, 'Suspendue'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée')], default=1, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='mrsrequestlogentry',
            name='action',
            field=models.SmallIntegerField(choices=[(1, 'Soumise'), (2, 'Modifiée'), (3, 'Effacée'), (100, 'Annulée'), (600, 'Suspendue'), (999, 'Rejetée'), (1000, 'En cours de liquidation'), (2000, 'Validée'), (800, 'Contacté')]),
        ),
    ]
