# Generated by Django 2.1.8 on 2019-04-25 00:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsrequest', '0039_mrsrequestlogentry_email_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mrsrequestlogentry',
            options={'ordering': ('-datetime',), 'verbose_name': 'Historique', 'verbose_name_plural': 'Historique'},
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='expensevp_parking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme totale des frais de stationnement (en € TTC)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de stationnement'),
        ),
        migrations.AddField(
            model_name='mrsrequest',
            name='expensevp_toll',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme totale des frais de péage (en € TTC)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Frais de péage'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='expensevp',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Somme des frais de péage et stationnement (en € TTC)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total des frais'),
        ),
        migrations.AlterField(
            model_name='mrsrequest',
            name='pel',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9]{14}', message='Le numéro de PMET doit comporter 14 caractères alpha numériques')], verbose_name='Numéro de PMET'),
        ),
    ]
