# Generated by Django 2.0.5 on 2018-06-14 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0002_unique_finess'),
        ('caisse', '0002_caisse_meta_option_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('validation_average_delay', models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True)),
                ('mrsrequest_count_total', models.IntegerField(editable=False)),
                ('mrsrequest_count_new', models.IntegerField(editable=False)),
                ('mrsrequest_count_validated', models.IntegerField(editable=False)),
                ('mrsrequest_count_rejected', models.IntegerField(editable=False)),
                ('insured_shift_count', models.IntegerField(editable=False)),
                ('savings', models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True)),
                ('caisse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='caisse.Caisse')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stat',
            unique_together={('date', 'caisse', 'institution')},
        ),
    ]
