# Generated by Django 2.0.5 on 2018-06-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='stat',
            name='insured_shift_count',
            field=models.IntegerField(editable=False, verbose_name='Nombre de bascules de TAP'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_new',
            field=models.IntegerField(editable=False, verbose_name='Nombre de nouvelles demandes'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_rejected',
            field=models.IntegerField(editable=False, verbose_name='Nombre de demandes rejettées'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_total',
            field=models.IntegerField(editable=False, verbose_name='Nombre total de demandes'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_validated',
            field=models.IntegerField(editable=False, verbose_name='Nombre de demandes validées'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='savings',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='stat',
            name='validation_average_delay',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, null=True, verbose_name='Délai moyen de paiement (en jours)'),
        ),
    ]
