# Generated by Django 2.0.5 on 2018-06-15 16:43

from django.core.management import call_command
from django.db import migrations, models

def update(apps, schema_editor):
    MRSRequest = apps.get_model('mrsrequest', 'MRSRequest')
    for m in MRSRequest.objects.all():
        m.save()

    Stat = apps.get_model('mrsstat', 'Stat')
    for s in Stat.objects.all():
        s.save()

    call_command('mrsstat')


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0002_labels_and_decimal_digits'),
    ]

    operations = [
        migrations.RunPython(update),
    ]
