# Generated by Django 2.0.5 on 2018-06-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0003_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stat',
            options={'ordering': ('date', 'caisse', 'institution')},
        ),
        migrations.RemoveField(
            model_name='stat',
            name='insured_shift_count',
        ),
        migrations.RemoveField(
            model_name='stat',
            name='mrsrequest_count_total',
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_new',
            field=models.IntegerField(editable=False, verbose_name='Nombre de demandes soumises'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='savings',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9, null=True, verbose_name='Econnomie réalisée'),
        ),
    ]
