# Generated by Django 2.0.5 on 2018-06-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0004_change_denorm'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='insured_shifts',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre de bascules'),
        ),
    ]
