# Generated by Django 2.1 on 2018-08-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0005_stat_insured_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_count_inprogress',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre de demandes en cours'),
            preserve_default=False,
        ),
    ]
