# Generated by Django 2.1 on 2018-09-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0006_stat_mrsrequest_count_inprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='insured_shifts_total',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre cumulé de bascules'),
        ),
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_total_inprogress',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre cumulé de demandes en cours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_total_new',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre cumulé de demandes soumises'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_total_rejected',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre cumulé de demandes rejettées'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_total_validated',
            field=models.IntegerField(default=0, editable=False, verbose_name='Nombre cumulé de demandes validées'),
            preserve_default=False,
        ),
    ]
