# Generated by Django 2.1.6 on 2019-02-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0007_totals'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_count_conflicted',
            field=models.IntegerField(default=0, help_text='Nb. affichages page de confirmation'),
        ),
        migrations.AddField(
            model_name='stat',
            name='mrsrequest_count_conflicting',
            field=models.IntegerField(default=0, help_text='Nb. conflicts soumis'),
        ),
    ]
