# Generated by Django 2.1.8 on 2019-04-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsstat', '0009_add_stat_mrsrequest_count_resolved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_conflicted',
            field=models.IntegerField(default=0, verbose_name='Nb. affichages page de confirmation'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='mrsrequest_count_conflicting',
            field=models.IntegerField(default=0, verbose_name='Nb. demandes soumises avec conflit non resolu'),
        ),
    ]
