# Generated by Django 2.1.6 on 2019-02-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrsrequest', '0036_multiple_pmts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField()),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('mrsrequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrsrequest.MRSRequest')),
            ],
            options={
                'ordering': ['-creation_datetime'],
            },
        ),
    ]
