# Generated by Django 2.1.6 on 2019-02-27 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caisse', '0004_caisse_import_datetime'),
        ('mrsrequest', '0036_multiple_pmts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[(None, '---------'), ('request_error', "J'ai fait une erreur de saisie dans mon dossier"), ('request_question', "J'ai une question sur mon dossier"), ('website_question', "J'ai une idée d'amélioration pour votre site"), ('other', 'Autre sujet')], db_index=True, max_length=25, verbose_name='motif')),
                ('name', models.CharField(max_length=255, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('creation_datetime', models.DateTimeField(auto_now=True)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caisse.Caisse')),
                ('mrsrequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mrsrequest.MRSRequest')),
            ],
            options={
                'ordering': ('-creation_datetime',),
            },
        ),
    ]
