# Generated by Django 2.2.3 on 2019-08-22 08:31
import os

from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations


def adduser(apps, schema_editor):
    if os.getenv('CI'):
        return

    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))

    if settings.SECRET_KEY != 'notsecret':
        return

    user, created = User.objects.get_or_create(
        username='test',
        is_superuser=True,
        is_active=True,
    )

    if created:
        user.password = make_password('test')
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0001_squashed_migrations'),
    ]

    operations = [
        migrations.RunPython(adduser)
    ]
