# Generated by Django 2.2.3 on 2019-09-03 11:47

from django.db import migrations


def adminlocal(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(
        name='Admin Local',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0002_auto_adduser'),
    ]

    operations = [
        migrations.RunPython(adminlocal),
    ]
