# Generated by Django 2.0.5 on 2018-06-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0002_user_caisses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
