# Generated by Django 2.1.3 on 2018-11-03 20:47

from django.db import migrations, models
import mrsuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0004_user_profile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', mrsuser.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='caisses',
            field=models.ManyToManyField(null=True, to='caisse.Caisse'),
        ),
    ]
