# Generated by Django 2.1 on 2018-11-05 21:55

from django.db import migrations, models
import mrsuser.models


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0005_nonschematic_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
