# Generated by Django 2.1.6 on 2019-04-10 07:52

from django.db import migrations


def add_superviseur(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Superviseur')


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0006_add_is_superuser'),
    ]

    operations = [
        migrations.RunPython(add_superviseur),
    ]
