# Generated by Django 2.1 on 2018-11-06 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrsuser', '0007_profile_to_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
