# Generated by Django 2.0.5 on 2018-06-29 05:58

from django.db import migrations, models


def insured_shift(apps, schema_editor):
    Person = apps.get_model('person', 'Person')
    for p in Person.objects.all():
        for m in p.mrsrequest_set.all():
            if m.insured_shift:
                p.shifted = True
                p.save()
                break

        if p.shifted:
            for m in p.mrsrequest_set.all():
                m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('mrsrequest', '0010_decimal_digits'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='shifted',
            field=models.NullBooleanField(default=None, verbose_name='Assuré a basculé'),
        ),
        migrations.RunPython(insured_shift),
    ]
