# Generated by Django 2.0 on 2017-12-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='nir',
            field=models.BigIntegerField(verbose_name='Numéro de sécurité sociale'),
        ),
    ]
