# Generated by Django 2.0.5 on 2018-07-03 10:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_insured_shift_move_to_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True, validators=[django.core.validators.MinValueValidator(datetime.date(1900, 1, 1))], verbose_name='Date de naissance'),
        ),
    ]
