# Generated by Django 2.1.2 on 2018-10-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20181029_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='use_email',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="L'assuré autorise à utiliser son email."),
        ),
    ]
