# Generated by Django 2.1 on 2018-12-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_person_use_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='confirms',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de signalements faits a l'assuré", verbose_name='Nb. signalements'),
        ),
    ]
