# Generated by Django 2.1.4 on 2019-01-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_nir_charfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='confirms',
            new_name='conflicts_accepted',
        ),
        migrations.AlterField(
            model_name='person',
            name='conflicts_accepted',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de signalements acceptés par l'utilisateur", verbose_name='Nb. signalements acceptés'),
        ),
        migrations.AddField(
            model_name='person',
            name='conflicts_resolved',
            field=models.PositiveIntegerField(default=0, help_text="Nombre de signalements résolus par l'utilisateur", verbose_name='Nb. signalements résolus'),
        ),
    ]
