# Generated by Django 2.2.3 on 2019-09-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_conflicts_counter_rewrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='conflicts_accepted',
        ),
        migrations.RemoveField(
            model_name='person',
            name='conflicts_resolved',
        ),
    ]
