# Generated by Django 2.2.3 on 2019-10-15 12:52

from django.db import migrations, models
import django.utils.timezone


def update_person_creation_datetime(apps, schema_editor):
    Person = apps.get_model('person', 'person')
    for p in Person.objects.all():
        m = p.mrsrequest_set.order_by('creation_datetime').first()
        p.creation_datetime = m.creation_datetime
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_remove_conflicts_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='creation_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Date et heure de la demande'),
        ),
        migrations.RunPython(update_person_creation_datetime),
    ]
