# Generated by Django 2.2.3 on 2019-11-22 15:33

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_person_creation_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='creation_datetime',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure de création'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[\\w –−-]+$', 'Merci de saisir uniquement lettres et tirets'), django.core.validators.RegexValidator('^[^\\d_]+$', 'Merci de saisir uniquement lettres et tirets')], verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=70, validators=[django.core.validators.RegexValidator('^[\\w –−-]+$', 'Merci de saisir uniquement lettres et tirets'), django.core.validators.RegexValidator('^[^\\d_]+$', 'Merci de saisir uniquement lettres et tirets')], verbose_name='Nom de famille'),
        ),
    ]
