---
- hosts: '*'
  tasks:
  - name: Notification de pré-déploiement sur slack
    when: lookup("env", "SLACK_TOKEN")
    tags: update
    slack:
      token: '{{ lookup("env", "SLACK_TOKEN") }}'
      username: Django
      color: warning
      channel: tech
      msg: |
        DEBUT du déploiement
        sur {{ lookup("env", "HOST") }}
        pour le commit {{ lookup("env", "DRONE_COMMIT_MESSAGE") }}
        par {{ lookup("env", "DRONE_COMMIT_AUTHOR_NAME") }}
        dans {{ lookup("env", "DRONE_BUILD_LINK") }}

  - include: backup.yml
    when: home is defined and lookup('env', 'RESTIC_PASSWORD')

  - name: Augmentation du nombre de connections simultannées à 256
    when: lookup('env', 'MAXCONN')
    sysctl:
      name: net.core.somaxconn
      value: '{{ lookup("env", "MAXCONN") }}'
      state: present

  - name: Déploiement du pod docker-compose
    include_role: name=yourlabs.compose
    vars:
      postdeploy: >
        {% if project is defined %}
        docker-compose exec -T django djcli dbcheck;
        docker-compose exec -T --env CI=1 django mrs loaddata src/mrs/tests/data.json;
        docker-compose exec -T django djcli save settings.AUTH_USER_MODEL +username=dev is_superuser=True;
        docker-compose exec -T django djcli chpasswd username=dev dev;
        {% endif %}

  - name: Configuration des logrotates
    copy:
      dest: /etc/logrotate.d/mrs
      content: |
        /home/*/log/*.log {
          daily
          missingok
          rotate 36
          compress
          notifempty
          create 0640 1000 1000
          sharedscripts
        }

  - name: Execution du healthcheck
    include_tasks: check.yml
