---

- name: Update docker-image
  tags: update,docker-run
  copy:
    content: '{{ image }}'
    dest: '{{ home }}/docker-image'
    mode: 0700
    owner: deploy
    unsafe_writes: true

- name: Update docker-run.sh
  tags: docker-run
  template:
    src: docker-run.sh
    dest: '{{ home }}/docker-run.sh'
    mode: 0700
    owner: root

- name: Execute docker-run.sh
  tags: update, docker-run
  shell: sudo {{ home }}/docker-run.sh
