---

- name: Configure logrotate for the log volume
  copy:
    dest: /etc/logrotate.d/{{ project_instance }}
    content: |
      {{ log_home }}/*.log {
        daily
        missingok
        rotate 36
        compress
        notifempty
        create 0640 1000 1000
        sharedscripts
      }

