---

- name: Install htaccess
  when: htaccess
  tags: users
  vars:
    htaccess_dns: '{{ dns }}'
    htaccess_service: '{{ project_instance }}'
  include_role:
    name: nginx_htpasswd

# not that fast: wait for actual use case to enable
# - name: Get custom nginx configuration from the image if any
#   shell: '{{ exec }} bash -c "test ! -f /app/etc/nginx.conf || cat /app/etc/nginx.conf"'
#   register: nginx_config

- name: Configure nginx
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ dns }}'
    content: |
      client_max_body_size 10M;
      client_body_buffer_size 10M;
      uwsgi_buffering off;

- name: Configure nginx for redirects
  with_items: '{{ dns_redirect }}'
  copy:
    dest: '{{ nginx_home|default("/home/nginx/") }}vhosts.d/{{ item }}_location'
    content: rewrite ^/(.*) https://{{ dns }}/$1 permanent;
