# Generated by Django 2.0.2 on 2018-03-12 10:43

from django.db import migrations, models




class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('number', models.PositiveIntegerField(verbose_name='numéro')),
                ('liquidation_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email vers les liquidateureuses')),
                ('active', models.BooleanField(default=False, verbose_name='activé')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
