# Generated by Django 2.0.4 on 2018-04-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caisse',
            options={'ordering': ['name']},
        ),
    ]
