# Generated by Django 2.2.3 on 2019-12-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_squashed_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='nopmt_enable',
            field=models.BooleanField(default=True, verbose_name='active la convocation sans PMT'),
        ),
    ]
