# Generated by Django 2.0.2 on 2018-03-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0003_field_number_to_varchar'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
