# Generated by Django 2.0.2 on 2018-03-15 09:45

from django.db import migrations


def format_caisse_number(apps, schema_editor):
    Caisse = apps.get_model('caisse', 'Caisse')
    for caisse in Caisse.objects.all():
        caisse.number = '{:03d}'.format(int(caisse.number))
        caisse.save()


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0005_liquidation_email_help_text'),
    ]

    operations = [
        migrations.RunPython(format_caisse_number),
    ]
