# Generated by Django 2.2.3 on 2019-09-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_caisse_load_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='habilitation_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="email du service d'habilitation"),
        ),
    ]
