# Generated by Django 2.0.2 on 2018-03-15 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0006_fix_number_formating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caisse.Caisse')),
            ],
        ),
    ]
