# Generated by Django 2.0.2 on 2018-03-15 10:05

from django.db import migrations


def activate_toulouse(apps, schema_editor):
    Caisse = apps.get_model('caisse', 'Caisse')
    toulouse = Caisse.objects.get(number=311)
    toulouse.liquidation_email = 'remboursement_mrs@cpam-toulouse.cnamts.fr'
    toulouse.active = True
    toulouse.save()


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0007_email'),
    ]

    operations = [
        migrations.RunPython(activate_toulouse),
    ]
